name: Smart Retail Build Pipeline

on:

 push:

   branches:

     - main

jobs:

 build:

   runs-on: ubuntu-latest

   steps:

   - name: Checkout Code

     uses: actions/checkout@v4

   - name: Install Node

     uses: actions/setup-node@v4

     with:

       node-version: 20

   - name: Install Dependencies

     run: |

       cd services/catalog-services

       npm install

   - name: Run Tests

     run: |

       cd services/catalog-services

       npm test

   - name: Build Docker Image

     run: |

       cd services/catalog-services

       docker build -t catalog-service:ci .
